name: build
env:
  MIX_ENV: test
  POSTGRES_HOST: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    services:
      db:
        image: postgres:latest
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install -y git
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get deps cache
      uses: actions/cache@v1
      with:
        path: deps/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-
    - name: Get build cache
      uses: actions/cache@v1 
      with:
        path: _build/test/
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-
    - name: Install Dependencies
      env:
        MIX_ENV: test
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile
    - name: Setup database
      run: |
        mix do ecto.create, ecto.migrate
    - name: Run Tests
      run: |
        mix credo
        mix test
