name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
    - uses: actions/checkout@v1
    - name: Get deps cache
      uses: actions/cache@v1
      with:
        path: deps/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-
    - name: Get build cache
      uses: actions/cache@v1 
      with:
        path: _build/test/
        key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-
    - name: Install Dependencies
      env:
        MIX_ENV: "test"
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      env:
        MIX_ENV: "test"
      run: |
        mix test
        mix coveralls.json
        mix credo
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: cover/excoveralls.json

